config/routes.rb
Rails.application.routes.draw do

  resources :nirs
  match 'requests/destroy_all',    to: 'requests#destroy_all',          via: 'get'
  match 'requests/epsh',    to: 'requests#epsh',          via: 'get'
  resources :two_criteria
  resources :requests
  resources :assessments
  resources :criteria
  resources :universities
  # Serve websocket cable requests in-process
  mount ActionCable.server => '/cable'

  # scope '(:locale)' do
  # scope "(:locale)" do #, :locale => /en|ru/ do



  resources :themes
  # get 'work/index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'main#index'
  get 'main/help'
  get 'main/contacts'
  get 'main/about'

  resources :values
  resources :images
  resources :microposts
  resources :users
  resources :sessions, only: [:new, :create, :destroy]


  # Api definition
  namespace :api, defaults: { format: :json } do
    # We are going to list our resources here
    #   resources :users

    match 'next_image',       to: 'api#next_image',   via: 'get'
    match 'prev_image',       to: 'api#prev_image',   via: 'get'
    match 'save_value',       to: 'api#save_value',   via: :get

  end


  match 'index',    to: 'main#index',           via: 'get'
  match 'about',    to: 'main#about',           via: 'get'
  match 'help',     to: 'main#help',            via: 'get'
  match 'contacts', to: 'main#contacts',        via: 'get'

  match 'work',             to: 'work#index',             via: 'get'
  match 'choose_image',     to: 'work#choose_image',      via: :get
  match 'choose_theme',     to: 'work#choose_theme',      via: :get
  match 'display_theme',    to: 'work#display_theme',     via: :post
  # match 'next_image',       to: 'work#next_image',   via: 'get'

  # match 'prev_image',       to: 'work#prev_image',   via: 'get'
  match 'results_list',     to: 'work#results_list', via: :get
  # match 'save_value',       to: 'work#save_value',      via: :get

  # api
  # match 'next_image',       to: 'api/api#next_image',   via: 'get'
  # match 'prev_image',       to: 'api/api#prev_image',   via: 'get'
  match 'save_value',       to: 'api/api#save_value',   via: :get



  match 'signup',   to: 'users#new',            via: 'get'
  match 'signin',   to: 'sessions#new',         via: 'get'
  match 'signout',  to: 'sessions#destroy',     via: 'delete'


  match 'ask',                     to: 'ask#index',                     via: 'get'
  match 'ask/update_request',      to: 'ask#update_request',            via: 'get'





  # end

end

app/views/shared/_footer.haml
%footer.footer
  -#%p Experteese
    -#{style: " display:inline-block; font-size: 1em"}
    -#2016
  -#%small
  -#  The
  -#  %a{:href => "http://www.railstutorial.org/"} Ruby on Rails Tutorial
  -#  by
  -#  %a{:href => "http://www.michaelhartl.com/"} Michael Hartl
  %h3{style: "color: #c4f7ff; font-size: 1.3em; position: relative; left: 20%; margin-top: .55em;"}
    Experteese
    %i.fa.fa-copyright.iconsMain{ style: " font-size: 1.3em; " }
    2016
    %p.app_notice_dev{style: " font-size: 1em; position: relative; left: 40%;"}
      %span{ style: "color: #730E15; font-size: 1.3em; position: relative; left: 11%;" }
        %i.fa.fa-flag.iconsMain{ style: "color: #efe3ff; font-size: .5em; " }
          = t('.dev_msg')


  .footer_menu
    %nav
      %ul
        %li= link_to t('.about'), about_path
        %li= link_to t('.contact'), contacts_path
        -#%li
        -#  %a{:href => "http://news.railstutorial.org/"} News

app/views/shared/_header.haml
%header.navbar.navbar-fixed-top.navbar-inverse
  .container.header
    .container
      = link_to t('.logo_title'), root_path, id: "logo"
      .rails_logo
        = link_to image_tag("rails.png", alt: "Rails logo")

        %p.locale
          = link_to image_tag("Russia.jpg", alt: "",  style: "width: 10%; height: 10%", title: "Русский" ), locale: :ru
          = link_to image_tag("United_Kingdom.jpg", alt: "",  style: "width: 12%; height: 12%", title: "English"), locale: :en
          %b
            = I18n.locale


    .container
      %nav
        %ul.nav.navbar-nav.pull-right
          = render :partial =>'shared/menu', :locals => { :info => is_exist_info(@info) }
          - if signed_in?
            -#%li= link_to "Users", '#'
            %li.logged
              #{current_user.email}
            = gravatar_for current_user
            %li#fat-menu.dropdown
              %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
                %p
                  = t('.person')
                  %b.caret
              %ul.dropdown-menu
                %li= link_to t('.profile'), current_user
                %li= link_to t('.settings'), '#'
                %li.divider
                %li
                  = link_to t('.sign_out'), signout_path, method: "delete"
          - else
            %li= link_to t('.sign_in'), signin_path

app/views/shared/_menu.html.haml
- @menu = { '0'=>{'title'=> t('.home'), 'path'=> "/", "children"=>{'0'=>{'title'=> "Главная2", 'path'=> "/"}}} ,
'1'=>{'title'=> "Пары критериев", 'path'=> "/two_criteria"},
'2'=>{'title'=> "Критерии", 'path'=> "/criteria"},
'3'=>{'title'=> "Научные работы", 'path'=> "/nirs"},
'5'=>{'title'=> "История ЗАПРОС", 'path'=> "/requests"},
'6'=>{'title'=> "Оценки", 'path'=> "/assessments"},}

-# '3'=>{'title'=> t('.contact'), 'path'=> "/main/contacts"},
-# '4'=>{'title'=> t('.about'), 'path'=> "/main/about"}

- @menu.each do |key, value|
  - if value['title'] == @info
    .current
    %li= link_to value['title'], value['path']
  - else
    %li= link_to value['title'], value['path']

-# menu_tag(@menu)
/  - attributes[:class] = "one two"
/  - node["title"]
/